test: add test that `/` performs true division, not floor division
ibis-project/ibis pull request #10359
Opened 2024-10-23 21:33 UTC by NickCrews

I can file an issue to track the actual flink fix for this if you want.

2024-10-24 12:47 UTC, cpcloud requested changes
Seems like a test-only PR here isn't going to do much beyond add an epsilon amount of time to overall test runs.

I'll poke at fixing this.

2024-10-24 12:52 UTC, cpcloud approved these changes

2024-10-31 14:23 UTC, cpcloud approved these changes

2024-10-31 14:23 UTC, merged

2024-10-31 16:59 UTC, NickCrews commented
Thanks @cpcloud! Nice job tag teaming this