feat(polars): add Intersection and Difference ops
ibis-project/ibis pull request #10623
Opened 2024-12-27 21:55 UTC by IndexSeek

## Description of changes

Adds support for [`Intersection`](https://ibis-project.org/reference/operations.html#ibis.expr.operations.relations.Intersection) and [`Difference`](https://ibis-project.org/reference/operations.html#ibis.expr.operations.relations.Difference) operations for the Polars backend. The approach uses pl.SQLContext to register the dataframes and query using [INTERSECT](https://docs.pola.rs/api/python/stable/reference/sql/set_operations.html#intersect) and [EXCEPT](https://docs.pola.rs/api/python/stable/reference/sql/set_operations.html#except), respectively. 

I saw that a few other functions used a `ctx` argument which might be using `pl.SQLContext` in a similar manner, I wasn't sure if that argument could be used here to avoid some of the boilerplate. Here are some of those functions I am referring to:

https://github.com/ibis-project/ibis/blob/28bafd14153cb7bb5bcc44063975f9346d55b76a/ibis/backends/polars/compiler.py#L69-L72

https://github.com/ibis-project/ibis/blob/28bafd14153cb7bb5bcc44063975f9346d55b76a/ibis/backends/polars/compiler.py#L1287-L1297

2024-12-28 13:17 UTC, cpcloud commented
@IndexSeek Thanks for the PR as always 😄 

I think it's reasonable to reuse the `ctx` argument in your implementations here rather than constructing a new `SQLContext`.

2024-12-28 14:42 UTC, IndexSeek commented
> @IndexSeek Thanks for the PR as always 😄
> 
> I think it's reasonable to reuse the `ctx` argument in your implementations here rather than constructing a new `SQLContext`.

You're welcome! That seems like a good plan. I gave this a try using the `ctx` from kwargs. I was experimenting with a way to reuse the existing tables as part of the context, but for some reason when I was doing `op.left.name` it would work standalone but when running tests I would get things like:

AttributeError: 'Sort' object has no attribute 'name'

This was working for me when using a memtable in an IPython shell, but not on the tests. 

Do you know if there is a more efficient way than needing to manually register the tables as "left" and "right"? 

Here's what I was trying where it seems to work using `op.left.name`, etc.:

```py
@translate.register(ops.Difference)
def execute_difference(op, **kw):
    ctx = kw.get("ctx")
    sql = (
        sg.select(STAR)
        .from_(sg.to_identifier(op.left.name, quoted=True))
        .except_(sg.select(STAR).from_(sg.to_identifier(op.right.name, quoted=True)))
    )
    result = ctx.execute(sql.sql(Polars), eager=False)
    if op.distinct is True:
        return result.unique()
    return result
```

```pycon
In [1]: from ibis.interactive import *
   ...: 
   ...: ibis.set_backend("polars")
   ...: 
   ...: t1 = ibis.memtable({"number_col": [1, 2, 3]})
   ...: t2 = ibis.memtable({"number_col": [2, 3, 4]})
   ...: t1.difference(t2)
Out[1]: 
┏━━━━━━━━━━━━┓
┃ number_col ┃
┡━━━━━━━━━━━━┩
│ int64      │
├────────────┤
│          1 │
└────────────┘
```

2024-12-30 11:35 UTC, cpcloud requested changes

2024-12-30 11:35 UTC, cpcloud commented on ibis/backends/polars/compiler.py
> +            "right": translate(op.right, **kw),
```suggestion
def execute_intersection(op, *, ctx, **kw):
    ctx.register_many(
        frames={
            "left": translate(op.left, ctx=ctx **kw),
            "right": translate(op.right, ctx=ctx, **kw),
```

2024-12-30 11:35 UTC, cpcloud commented on ibis/backends/polars/compiler.py
> +            "right": translate(op.right, **kw),
```suggestion
def execute_difference(op, *, ctx, **kw):
    ctx.register_many(
        frames={
            "left": translate(op.left, ctx=ctx, **kw),
            "right": translate(op.right, ctx=ctx, **kw),
```

2024-12-30 13:13 UTC, cpcloud approved these changes

2024-12-30 13:13 UTC, merged

2024-12-30 13:13 UTC, cpcloud commented
@IndexSeek Thank you!