TST: mark failing BigQuery tests as xfail
ibis-project/ibis pull request #2375
Opened 2020-09-10 15:36 UTC by tswast

It appears that most of these issues are due to changes in how a
DataFrame is created in the `google-cloud-bigquery` library. Now that
Arrow is used as an intermediate format, arrays and structs come back as
numpy arrays or Arrow objects. Previously they came back as Python
objects (lists and dictionaries).

Closes #2353

2020-09-12 20:55 UTC, jreback requested changes

2020-09-12 20:55 UTC, jreback commented on ibis/bigquery/tests/test_client.py
> +@pytest.mark.xfail  # Issue 2374
can you add reason= here with the issue number, also add strict=True

2020-09-16 16:55 UTC, datapythonista approved these changes
Thanks @tswast lgtm.

Should this fix the bigquery build? Or more work is needed?

2020-09-16 17:54 UTC, tswast commented
It should "fix" the build for all the issues you identified in #2353. 

I haven't investigated all the new failures around floating point values yet https://github.com/ibis-project/ibis/issues/2353#issuecomment-692067685

2020-09-16 19:22 UTC, jreback approved these changes

2020-09-16 19:22 UTC, merged

2020-09-16 19:23 UTC, jreback commented
thanks @tswast obviously happy to have patches for these.