Move Spark backend to backends/ directory
ibis-project/ibis pull request #2434
Opened 2020-10-01 18:43 UTC by EdAbati

As part of the Ibis sprint, I am making this PR that closes #2416

Please let me know if if and how I can improve it.

Thanks,

2020-10-01 18:48 UTC, datapythonista reviewed
Thanks @EdAbati, nice work. Just few changes in the imports, but looks good.

2020-10-01 18:48 UTC, datapythonista commented on ibis/__init__.py
> +    import ibis.backends as spark  # noqa: F401
```suggestion
    from ibis.backends import spark  # noqa: F401
```

2020-10-01 18:48 UTC, datapythonista commented on ibis/backends/spark/tests/test_ddl_compilation.py
> +from ibis.backends.spark.compiler import (  # noqa: E402, isort:skip
```suggestion
from .compiler import (  # noqa: E402, isort:skip
```

2020-10-01 18:48 UTC, datapythonista commented on ibis/backends/spark/tests/test_ddl_compilation.py
> +from ibis.backends.spark import ddl  # noqa: E402, isort:skip
```suggestion
from . import ddl  # noqa: E402, isort:skip
```

2020-10-01 18:48 UTC, datapythonista commented on ibis/backends/spark/tests/test_udf.py
> +from ibis.backends.spark.udf import udf  # noqa: E402, isort:skip
```suggestion
from .udf import udf  # noqa: E402, isort:skip
```

2020-10-01 18:48 UTC, datapythonista commented on ibis/backends/spark/tests/test_udf.py
> +    from ibis.backends.spark import _SPARK_DTYPE_TO_IBIS_DTYPE
```suggestion
    from . import _SPARK_DTYPE_TO_IBIS_DTYPE
```

2020-10-01 19:26 UTC, icexelloss requested changes
Please do not merge. Let me investigate CI.

2020-10-06 14:58 UTC, datapythonista commented
/azp run

2020-10-06 17:31 UTC, jreback commented
lgtm, conflict.

2020-10-07 11:16 UTC, datapythonista commented
@icexelloss can we merge this already? I guess we can be confident about the tests after #2442, right?

2020-10-07 12:14 UTC, jreback approved these changes

2020-10-07 12:14 UTC, merged

2020-10-07 12:15 UTC, jreback commented
thanks @EdAbati