FEAT: add hashbytes function to string and binary expressions
ibis-project/ibis pull request #2508
Opened 2020-10-30 19:31 UTC by tswast

Also, support `farm_fingerprint` hash type in the BigQuery engine.

Closes #2310

2020-10-30 21:27 UTC, jreback requested changes
lgtm. (minor comment). are these available on other sql backends? if so would love to have a followup which implements. pandas implements here: https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.util.hash_pandas_object.html?highlight=hash#pandas.util.hash_pandas_object

2020-10-30 21:27 UTC, jreback commented on ibis/backends/base_sql/__init__.py
> +        return 'md5({})'.format(arg_formatted)
these can be f-strings, but nbd.

2020-10-30 21:27 UTC, jreback requested changes
can you add a whatsnew note and ping on green.

2020-11-04 04:28 UTC, jreback commented
can u merge master

2020-11-04 15:51 UTC, tswast commented
@jreback Merged! The build is green now.

2020-11-04 16:50 UTC, jreback approved these changes

2020-11-04 16:51 UTC, merged

2020-11-04 16:51 UTC, jreback commented
thanks @tswast very nice