Copy ibis feedstock recipe
ibis-project/ibis pull request #2527
Opened 2020-11-13 19:08 UTC by matthewmturner

closes #2523 

@datapythonista

2020-11-13 19:18 UTC, datapythonista reviewed
Looks good, just two things that will make the CI and need to be removed, but other than that looks good.

2020-11-13 19:18 UTC, datapythonista commented on ci/recipe/meta.yaml
> +
Can you remove this? We edit this file via bash for the packaging build, and I think we add this automatically.

2020-11-13 19:18 UTC, datapythonista commented on ci/recipe/meta.yaml
> +  sha256: dd3e3d6d495d4ed4f7e5b8ec523949bc54f6fc89f31ca60ef3dc103de8d37635
Same here.

2020-11-13 19:54 UTC, datapythonista approved these changes
Great, thanks for taking care of this @matthewmturner

2020-11-14 17:04 UTC, jreback requested changes
tiny comment, let's see this build correctly (docs build), though unrelated i think.

2020-11-14 17:04 UTC, jreback commented on ci/recipe/meta.yaml
> +    - datapythonista
blank line at the end

2020-11-14 18:22 UTC, jreback approved these changes

2020-11-15 17:09 UTC, merged

2020-11-15 17:09 UTC, jreback commented
thanks @matthewmturner