Update to pandas.testing
ibis-project/ibis pull request #2540
Opened 2020-11-21 05:11 UTC by matthewmturner

Closes #2539

2020-11-21 16:34 UTC, jreback requested changes

2020-11-21 16:34 UTC, jreback commented on ibis/backends/impala/tests/test_pandas_interop.py
> -from pandas.util.testing import assert_frame_equal
can you change these to
`import pandas.testing  as tm` to be consitent

2020-11-21 16:34 UTC, jreback commented on ibis/backends/pandas/tests/execution/test_cast.py
> -import pandas.util.testing as tm  # noqa: E402
if you can remove the noqa (if its not needed then remove the import)

2020-11-21 16:34 UTC, jreback commented on ibis/backends/sqlite/tests/test_functions.py
> -import pandas.util.testing as tm  # noqa: E402
same for all

2020-11-26 10:46 UTC, datapythonista commented
/azp run

2020-11-26 10:47 UTC, datapythonista approved these changes
Great cleanup @matthewmturner, thanks for working on this.

@jreback all your comments are addressed, if you want to have another look.

2020-11-26 11:12 UTC, datapythonista commented
@matthewmturner there are couple of errors in the CI, not sure why those functions are not in `pandas.testing` anymore, can you have a look please?

2020-11-27 06:24 UTC, matthewmturner commented
could it be related to #2538 which is now raising test failures compared to my first commit when these tests passed?

I also only see the following 4 functions in `pandas.testing` from both documentation and checking directly.

```
In [1]: import pandas.testing as tm

In [2]: dir(tm)
Out[2]: 
['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'assert_extension_array_equal',
 'assert_frame_equal',
 'assert_index_equal',
 'assert_series_equal']
```

Is it expected that all functionality in  `pandas.util.testing` is in `pandas.testing`?

2020-12-02 14:38 UTC, matthewmturner commented
@datapythonista any thoughts here? Im happy to switch back to `pandas.util.testing` for the `makeDataframe` functionality thats missing in `pandas.testing`?  I had thought all functionality in `pandas.util.testing` would be `pandas.testing` but it appears not.

Seems like an easy fix just wanted to make sure it aligned to your expectations.

2020-12-03 12:21 UTC, datapythonista commented
I think `makeDataFrame` is not part of the pandas public API, and not supposed to be used outside of pandas, that's why it's not in pandas.testing. I think the "right" solution is to avoid using it and create the dataframe manually. Does this sound right @jreback ?

2020-12-03 13:01 UTC, jreback commented
yes - just create a test dataframe here instead

2020-12-07 23:36 UTC, matthewmturner commented
@jreback updated to manually creating test df. let me know if anything else.

2020-12-08 21:10 UTC, jreback approved these changes

2020-12-08 21:10 UTC, merged

2020-12-08 21:10 UTC, jreback commented
thanks @matthewmturner nice! keep em coming!

2020-12-08 22:12 UTC, matthewmturner commented
@jreback are there any issues you want prioritized for next release?

2020-12-08 22:44 UTC, datapythonista commented
> @jreback are there any issues you want prioritized for next release?

#2533 would be a really good one to have fixed

2020-12-08 22:46 UTC, matthewmturner commented
> 
> 
> > @jreback are there any issues you want prioritized for next release?
> 
> #2533 would be a really good one to have fixed

Ok - will give it a look.