BUG: Fixes issue #2692
ibis-project/ibis pull request #2699
Opened 2021-03-21 23:10 UTC by ivergara

This PR fixes an unexpected behavior when a `timestamp` column with `null` values and datetimes outside `pandas` supported range. It avoids raising an exception by reinterpreting the `None` value as a `pandas.NaT` like it's done in the case of datetimes within the supported range.

An example on how to set the table in the database can be found in the issue related to this PR.

2021-03-24 02:21 UTC, datapythonista commented
Thanks @ivergara. Can you add a test (that fails before this fix, and passes with the fix) and a release note. Also, can you please merge master into your branch.

2021-03-24 22:15 UTC, jreback requested changes
also pls merge master, the CI is now fixed.

2021-03-25 09:15 UTC, ivergara commented
Yes, will do a merge from master. I'm investigating where and how to write the test case.

2021-03-31 11:15 UTC, datapythonista commented
This could be a good location for the test I think: `ibis/backends/tests/test_temporal.py`.

Maybe you can start with a test similar to the code you wrote that caused the problem.

2021-04-04 18:18 UTC, ivergara commented
I have an issue concerning how to run the tests. If I do as written in the contribute section of the website it only executes the tests found in `ibis/tests` directory and not those in `ibis/backend/tests`. If I invike `pytest` as follow `python -m pytest .\ibis\backends\tests\test_temporal.py`, I get issues with postgres `sqlalchemy.exc.NoSuchTableError`  while in postgres I get `FATAL:  unsupported frontend protocol 1234.5680: server supports 2.0 to 3.0`. This happens with postgres 9.3 or 11, both running via docker and working on a Windows environment.

2021-04-06 13:14 UTC, datapythonista commented
> I have an issue concerning how to run the tests. If I do as written in the contribute section of the website it only executes the tests found in `ibis/tests` directory and not those in `ibis/backend/tests`. If I invike `pytest` as follow `python -m pytest .\ibis\backends\tests\test_temporal.py`, I get issues with postgres `sqlalchemy.exc.NoSuchTableError` while in postgres I get `FATAL: unsupported frontend protocol 1234.5680: server supports 2.0 to 3.0`. This happens with postgres 9.3 or 11, both running via docker and working on a Windows environment.

Backend tests connect to actual databases. To run them you need both the dependencies (database drivers...) and a database server (you can see the configuration paramters and which docker image to use in the CI file `.github/workflows/main.yml`.

There are some backends that don't require much, like `pandas` and `sqlite`. Locally I just run the tests for those:
```bash
$ PYTEST_BACKENDS="pandas sqlite" python -m pytest ibis/tests ibis/backends/tests ibis/backends/pandas/tests ibis/backends/sqlite/tests
```

2021-04-30 22:27 UTC, datapythonista commented
@ivergara do you still want to work on this?

2021-05-01 20:46 UTC, ivergara commented
@datapythonista yes, just haven't found the time to get into this. When I did try I didn't really manage to set up the test for the fix.

2021-05-03 15:56 UTC, datapythonista commented
> @datapythonista yes, just haven't found the time to get into this. When I did try I didn't really manage to set up the test for the fix.

Let me know if you have any specific question.

2021-05-18 18:29 UTC, datapythonista commented
I'll close this for now. Let me know if you have time to finish this @ivergara and more than happy to reopen. Thanks!

2021-05-18 18:29 UTC, closed without merging