Replace ops with compiles decorator by regular registry
ibis-project/ibis pull request #2729
Opened 2021-04-17 17:48 UTC by datapythonista

Having operations defined in two places make things more complex for no reason. Removing the `compiles` decorator for most backends, and using the regular registry instead.

`pyspark` seems to have mostly all operations defined using `compiles`. I think it'd make sense to have a registry like the other backends. And that would help if we move towards #2659. But will open an issue for that, and address it separately.

2021-04-17 18:01 UTC, datapythonista commented
This is blocked by #2727. Once the SQLAlchemy backend code is refactored, we need to move the ops there to its `registry.py` file, and remove the `compiles` decorator.

Also, there are couple of examples in the tutorial using the `compiles` decorator that need to be updated.

2021-05-03 12:21 UTC, jreback commented
can you merge master and let the ci run again here

2021-05-03 13:20 UTC, jreback requested changes
rebase as well

2021-05-03 13:20 UTC, jreback commented on ibis/backends/base/sql/alchemy/translator.py
> +    import ibis.expr.types as ir
this doesn't make sense, these are standard ibis imports

2021-05-03 14:15 UTC, datapythonista commented
Rebased, still all green. Thanks @jreback 

I also moved the imports to the top. Agree that they belong here, but should be able to delete that function soon, so left them there to remove it quicker with all its imports. Not a big deal.

2021-05-03 14:31 UTC, jreback commented
> Rebased, still all green. Thanks @jreback
> 
> I also moved the imports to the top. Agree that they belong here, but should be able to delete that function soon, so left them there to remove it quicker with all its imports. Not a big deal.

thanks, yeah certainly removing that function is fine (followup)

2021-05-03 14:33 UTC, jreback approved these changes

2021-05-03 14:33 UTC, merged