ENH: Add __getstate__ and __setstate__ for Nodes
ibis-project/ibis pull request #2938
Opened 2021-09-07 18:14 UTC by patcao

2021-09-07 18:14 UTC, pep8speaks commented
Hello @patcao! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`ibis/tests/expr/test_table.py`](https://github.com/ibis-project/ibis/blob/a420643379e81b2c13e57477a3a8886694355164/ibis/tests/expr/test_table.py):

> [Line 1300:1](https://github.com/ibis-project/ibis/blob/a420643379e81b2c13e57477a3a8886694355164/ibis/tests/expr/test_table.py#L1300): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

2021-09-07 18:48 UTC, datapythonista commented
@patcao can you link an issue number if you're working on one. Or provide a description to know why you are proposing this change please. Thank you

2021-09-07 19:00 UTC, icexelloss commented on ibis/tests/expr/test_table.py
> +def test_pickle_table_node(table):
Can you add a few more test with more operations and UDFs?

2021-09-07 19:00 UTC, icexelloss commented on ibis/expr/operations.py
> +    def __getstate__(self):
Can you add docstring for these two method describing what you are doing and why?

2021-09-07 19:00 UTC, icexelloss commented on ibis/expr/operations.py
> +        excluded_slots = {'_expr_cached', '_hash'}
Can you add comment here why it's OK to exclude these fields for serialization

2021-09-07 19:05 UTC, icexelloss commented on ibis/expr/operations.py
> +        return {
I am not certain how it works when slot is another ibis TableExpr or ColumnExpr, can you explain it works?

2021-09-07 19:13 UTC, icexelloss commented
@datapythonista Chime in a little bit here about the rationale here. We are trying to build "consistent hash" for ibis Expression (hash that doesn't change cross Python interpreter restart for ibis Expression) and the current implementation depends on first pickling the ibis Expression then use sth like hashlib.sha256() to compute the hash from the pickled bytes. 

During this, we found that because ibis Node class that "_cached_expr" and "_hash" attributes, the pickled bytes can be different for the same table depending on whether those two fields are created, which is not a very desirable behavior. This PR aims to fix the ser/de method so that they produce consistent results for the equivalent  Node object.

2021-09-08 15:43 UTC, jreback requested changes
also pls add a release note

2021-09-08 22:04 UTC, jreback requested changes
minor comment. @icexelloss has a couple of comments. pls add a release note as well.

2021-09-08 22:04 UTC, jreback commented on ibis/expr/operations.py
> +    def __setstate__(self, state: Dict[str, Any]):
return -> None

2021-09-09 13:33 UTC, icexelloss approved these changes
LGTM

2021-09-09 13:35 UTC, jreback commented
@patcao can you add a release note. ping on green.

2021-09-09 17:26 UTC, jreback commented on docs/source/release/index.rst
> +* :feature:`2938` Add `__getstate__` and `__setstate__` methods to Node
can you just say, that serialization-deserialization via pickle is now byte compatible between different processes.

2021-09-09 19:01 UTC, jreback approved these changes

2021-09-09 19:02 UTC, merged

2021-09-09 19:02 UTC, jreback commented
thanks @patcao