docs: add fugue to ecosystems
ibis-project/ibis pull request #3374
Opened 2022-01-29 01:58 UTC by goodwanghan

2022-01-29 11:57 UTC, cpcloud requested changes
Awesome! Just a quick suggestion to move the imports up. Other than that, this is good to go.

2022-01-29 11:57 UTC, cpcloud commented on docs/web/community/ecosystem.md
> +from fugue import FugueWorkflow
```suggestion
import pandas as pd

import fugue_ibis
from fugue import FugueWorkflow


# schema: *,pred:double
def predict(df: pd.DataFrame) -> pd.DataFrame:
    model = load_model("somefile")
    return df.assign(pred=model.predict(df))

```

2022-01-29 17:54 UTC, goodwanghan commented on docs/web/community/ecosystem.md
> +from fugue import FugueWorkflow
Sure, I have fixed this @cpcloud

2022-01-29 18:26 UTC, cpcloud approved these changes
@goodwanghan Can you squash to a single commit? Thanks! Looks great!

2022-01-29 18:27 UTC, goodwanghan commented
Sure I will squash and merge.

Thank you!

2022-01-29 19:16 UTC, goodwanghan commented
@cpcloud will you squash and merge? or I need to squash it first?

2022-01-29 20:31 UTC, jreback reviewed
personally i would remove the actual code sample from here & the sql_to_ibis and just provide the prose & links. The home pages are fully formed and likely kept up to date.

2022-01-30 10:35 UTC, cpcloud commented
Merging on green! Thanks @goodwanghan!

2022-01-30 10:35 UTC, merged