experiment(ir): remove intermediate expressions
ibis-project/ibis pull request #3798
Opened 2022-04-21 13:37 UTC by kszucs

2022-04-21 13:52 UTC, jreback requested changes
can we keep the original values around for a while - this is a major breaking change

2022-04-21 14:01 UTC, kszucs commented
@jreback this is just a prototype where we can experiment with pattern matching on operation trees using matchpy

2022-04-24 20:28 UTC, kszucs commented on ibis/expr/operations/generic.py
> +class NullLiteral(Literal, Singleton):
Ohh how handy it is!

2022-04-24 20:33 UTC, kszucs commented
In order to allow proper pattern matching on ibis operations we would need to accept three kinds of arguments:
1. Expressions arriving from the standard usage of the API
2. `matchpy.Wildcard` and perhaps other `matchpy.Symbol` objects
3. ibis operations so we can substitute operations without converting to expression before construction 

These three ideally should be achieved by rewriting the current rules to return with ibis operations instead of expressions.

2022-06-08 08:33 UTC, pep8speaks commented
Hello @kszucs! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`ibis/common/graph.py`](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/common/graph.py):

> [Line 19:22](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/common/graph.py#L19): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 19:22](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/common/graph.py#L19): [E999](https://duckduckgo.com/?q=pep8%20E999) SyntaxError: invalid syntax
> [Line 19:24](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/common/graph.py#L19): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals

* In the file [`ibis/common/grounds.py`](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/common/grounds.py):

> [Line 198:80](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/common/grounds.py#L198): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)







* In the file [`ibis/expr/operations/core.py`](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/expr/operations/core.py):

> [Line 59:9](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/expr/operations/core.py#L59): [E999](https://duckduckgo.com/?q=pep8%20E999) SyntaxError: invalid syntax
> [Line 305:1](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/expr/operations/core.py#L305): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)



* In the file [`ibis/expr/pretty.py`](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/expr/pretty.py):

> [Line 4:1](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/expr/pretty.py#L4): [F401](https://duckduckgo.com/?q=pep8%20F401) 'sys' imported but unused
> [Line 6:1](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/expr/pretty.py#L6): [F401](https://duckduckgo.com/?q=pep8%20F401) 'matchpy.Symbol' imported but unused
> [Line 6:1](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/expr/pretty.py#L6): [F401](https://duckduckgo.com/?q=pep8%20F401) 'matchpy.is_match' imported but unused
> [Line 6:1](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/expr/pretty.py#L6): [F401](https://duckduckgo.com/?q=pep8%20F401) 'matchpy.match' imported but unused
> [Line 6:1](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/expr/pretty.py#L6): [F401](https://duckduckgo.com/?q=pep8%20F401) 'matchpy.op_iter' imported but unused
> [Line 6:1](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/expr/pretty.py#L6): [F401](https://duckduckgo.com/?q=pep8%20F401) 'matchpy.op_len' imported but unused
> [Line 6:1](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/expr/pretty.py#L6): [F401](https://duckduckgo.com/?q=pep8%20F401) 'matchpy.replace' imported but unused
> [Line 6:1](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/expr/pretty.py#L6): [F401](https://duckduckgo.com/?q=pep8%20F401) 'matchpy.replace_many' imported but unused
> [Line 6:1](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/expr/pretty.py#L6): [F401](https://duckduckgo.com/?q=pep8%20F401) 'matchpy.substitute' imported but unused
> [Line 24:1](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/expr/pretty.py#L24): [F401](https://duckduckgo.com/?q=pep8%20F401) 'ibis.expr.datatypes as dt' imported but unused
> [Line 28:1](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/expr/pretty.py#L28): [F401](https://duckduckgo.com/?q=pep8%20F401) 'ibis.expr.types as ir' imported but unused
> [Line 29:1](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/expr/pretty.py#L29): [F401](https://duckduckgo.com/?q=pep8%20F401) 'ibis.expr.window as win' imported but unused
> [Line 53:1](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/expr/pretty.py#L53): [F811](https://duckduckgo.com/?q=pep8%20F811) redefinition of unused 'create_operation_node' from line 48
> [Line 138:17](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/expr/pretty.py#L138): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'fmt_fields'
> [Line 139:9](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/expr/pretty.py#L139): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'op'
> [Line 142:17](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/expr/pretty.py#L142): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'fmt_selection_column'
> [Line 143:24](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/expr/pretty.py#L143): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'selection_maxlen'
> [Line 143:41](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/expr/pretty.py#L143): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'op'
> [Line 145:24](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/expr/pretty.py#L145): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'fmt_value'
> [Line 146:23](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/expr/pretty.py#L146): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'fmt_value'
> [Line 148:17](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/expr/pretty.py#L148): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'aliases'





* In the file [`ibis/tests/expr/test_match.py`](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/tests/expr/test_match.py):

> [Line 12:1](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/ibis/tests/expr/test_match.py#L12): [F401](https://duckduckgo.com/?q=pep8%20F401) 'ibis.expr.rules as rlz' imported but unused











* In the file [`match.py`](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/match.py):

> [Line 39:80](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/match.py#L39): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 40:80](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/match.py#L40): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (96 > 79 characters)
> [Line 51:9](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/match.py#L51): [E999](https://duckduckgo.com/?q=pep8%20E999) SyntaxError: invalid syntax
> [Line 105:80](https://github.com/ibis-project/ibis/blob/2be27c8f81d94e5dc51a1608fb86a4153a7ab739/match.py#L105): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)

2022-07-10 11:58 UTC, kszucs commented
Closing in favor of https://github.com/ibis-project/ibis/pull/4135

2022-07-10 11:58 UTC, closed without merging