feat: read_delta and to_delta for some backends
ibis-project/ibis pull request #6354
Opened 2023-06-01 20:17 UTC by lostmygithubaccount

closes #6319

adds `read_delta` for some backends and `to_delta` for all backends (writing locally)

TODO:
- [x] tests
~- [ ] datafusion backend~
~- [ ] spark backend?~ 
- [x] handling the dependency/import for deltalake
- [x] update some docstrings

2023-06-02 09:53 UTC, cpcloud commented
Regarding dependencies, I think we can make `deltalake` its own extra, to avoid requiring it for every backend including if someone won't ever need support for writing deltalake files.

I can push up the changes for that.

2023-06-02 11:27 UTC, cpcloud commented
Added a small round trip test.

2023-06-02 11:36 UTC, cpcloud commented
One issue with the spark implementation is that the recommended way to do this -- using `delta-spark` -- requires `pyspark` 3.4.0, which has terrible support for numpy 1.24 and pandas 2.

2023-06-02 11:36 UTC, cpcloud requested changes

2023-06-02 11:37 UTC, cpcloud commented on ibis/backends/polars/__init__.py
> +        Register a Delta Lake as a table in the current database.
```suggestion
        """Register a Delta Lake as a table in the current database.
```

2023-06-02 14:49 UTC, cpcloud commented
Pushed up a fix for the conflict.

2023-06-02 18:16 UTC, lostmygithubaccount commented on ibis/backends/duckdb/__init__.py
> +            delta_table.to_pyarrow_dataset().to_table(), table_name=table_name
does this need to be updated? I assumed only table/batch reader

2023-06-02 18:18 UTC, lostmygithubaccount commented
I think I'll skip Spark for this PR and can add later if requested? thanks for the help here! I'll look to add datafusion, update some docstrings, and look at adding moretests

2023-06-02 18:31 UTC, cpcloud commented on ibis/backends/duckdb/__init__.py
> +            delta_table.to_pyarrow_dataset().to_table(), table_name=table_name
Does to_table read the entire thing into memory? If so, we should remove that method call and let it remain a pyarrow dataset.

2023-06-02 18:33 UTC, lostmygithubaccount commented on ibis/backends/duckdb/__init__.py
> +            delta_table.to_pyarrow_dataset().to_table(), table_name=table_name
sorry I missed a link -- `to_table` does read it into memory, but pyarrow dataset as an input isn't noted here: https://github.com/ibis-project/ibis/blob/b23689372fa3d9c30651b69541c8945c1be38152/ibis/backends/duckdb/__init__.py#L447

2023-06-02 18:34 UTC, lostmygithubaccount commented on ibis/backends/duckdb/__init__.py
> +            delta_table.to_pyarrow_dataset().to_table(), table_name=table_name
and batches didn't seem to work (per my comment above on line 510)

2023-06-02 18:50 UTC, cpcloud commented on ibis/backends/duckdb/__init__.py
> +            delta_table.to_pyarrow_dataset().to_table(), table_name=table_name
Right, but try it without the to_table call, it should work. We may just need to update the docs/annotations.

2023-06-05 16:40 UTC, cpcloud approved these changes

2023-06-05 20:07 UTC, cpcloud commented
Fixed up a small issue from #6323 (replacing `self._tables` assignment with `self._add_table`).

Set to automerge!

2023-06-05 20:28 UTC, merged