fix(format): support rendering empty schemas
ibis-project/ibis pull request #6893
Opened 2023-08-18 07:05 UTC by kszucs

2023-08-18 08:15 UTC, cpcloud requested changes
I have a pull request up to remove support for empty schemas. Perhaps we can close this one?

2023-08-22 07:20 UTC, kszucs commented
@cpcloud How about merging this one to solve the immediate issue, then decide on whether we should allow empty schemas or not later on?

2023-09-09 08:58 UTC, cpcloud commented
@kszucs I missed you last message! I agree, let's merge this for now and revisit if it's a problem later.

2023-09-09 08:59 UTC, cpcloud approved these changes

2023-09-09 08:59 UTC, merged