docs: add copyright holders to license
ibis-project/ibis pull request #7249
Opened 2023-09-28 21:25 UTC by lostmygithubaccount

noticed this in the ibis-birdbrain repo, feel free to change directly or suggest other words

2023-09-28 21:28 UTC, lostmygithubaccount commented
unrelated docker failure that was noticed elsewhere?

2023-09-29 14:28 UTC, gforsyth requested changes
docker should fix itself when it re-runs

2023-09-29 14:28 UTC, gforsyth commented on LICENSE.txt
> +   Copyright Ibis developers
Needs a date to be valid

2023-11-07 14:22 UTC, gforsyth commented
Merging this in -- don't need CI to run on a license file.

2023-11-07 14:22 UTC, gforsyth commented
Wait, I lied, I _do_ need CI to run :shrug:

2023-11-07 14:41 UTC, merged