feature(exporting): allow passing writer_opts to PyArrow ParquetWriter and CSVWriter
ibis-project/ibis pull request #7570
Opened 2023-11-16 23:29 UTC by jayceslesar

Small tweak to allow passing of writer specific args/kwargs

2023-11-17 15:00 UTC, cpcloud commented on ibis/backends/base/__init__.py
> +            with pq.ParquetWriter(path, batch_reader.schema, **writer_opts) as writer:
How about instead passing `**kwargs`?

2023-11-17 15:00 UTC, cpcloud commented on ibis/backends/base/__init__.py
> +            with pcsv.CSVWriter(path, batch_reader.schema, **writer_opts) as writer:
Same as the Parquet version: How about instead passing `**kwargs`?

2023-11-17 15:02 UTC, cpcloud requested changes
Thanks for PR!

Can you add a test, one for each of parquet and csv code paths? Putting them in `ibis/backends/tests/test_export.py` is fine.

2023-11-17 15:45 UTC, jayceslesar commented on ibis/backends/base/__init__.py
> +            with pq.ParquetWriter(path, batch_reader.schema, **writer_opts) as writer:
```suggestion
            with pq.ParquetWriter(path, batch_reader.schema, **kwargs) as writer:
```

2023-11-17 15:45 UTC, jayceslesar commented on ibis/backends/base/__init__.py
> +            with pcsv.CSVWriter(path, batch_reader.schema, **writer_opts) as writer:
```suggestion
            with pcsv.CSVWriter(path, batch_reader.schema, **kwargs) as writer:
```

2023-11-17 18:17 UTC, jayceslesar commented
Working on adding tests but have had to exclude duckdb as its export options are not the same as pyarrow https://duckdb.org/docs/sql/statements/copy#csv-options

2023-11-17 19:53 UTC, jayceslesar commented
Heads up this is failing because the duckdb backend doesnt use the writers it just uses the duckdb copy kwargs, so I think we should exclude duckdb from this test unless we wanted it to dump normally, and then iterate the output in batches and stream to the parquet writer 🤷

2023-11-18 11:54 UTC, cpcloud commented
I opted for excluding duckdb from the tests you added.

Thank you for address my feedback!

2023-11-18 11:54 UTC, cpcloud approved these changes

2023-11-18 17:26 UTC, merged