docs: include return type in Interval.years, .months, etc
ibis-project/ibis pull request #8193
Opened 2024-02-01 22:25 UTC by NickCrews

Fixes https://github.com/ibis-project/ibis/issues/8165

2024-02-05 11:50 UTC, cpcloud commented
@NickCrews Thanks for the PR. Is there any chance that instead of this approach we can add these methods and properties individually to `_quarto.yml` (likely requiring `dynamic: true` for each of them)?

2024-03-05 19:04 UTC, NickCrews commented
[This is relevant](https://github.com/machow/quartodoc/issues/284). Now trying to poke around with the
```python
class A:
    attr_a: int
    """Docstring."""
```
format

2024-03-05 19:15 UTC, NickCrews commented
I think this is still a gradual improvement, even if it isn't ideal. I think it shouldn't be bad to reverse or improve this later if this functionality changes. At the least, it adds `__add__` documentation, which was missing.

2024-03-12 11:04 UTC, cpcloud requested changes

2024-03-12 11:04 UTC, cpcloud commented on docs/_quarto.yml
> +                - __floordiv__
```suggestion
```

We're probably going to get rid of these methods soon, they're extremely finicky and don't really work as advertised.

2024-03-12 21:28 UTC, cpcloud approved these changes
Thanks!

2024-03-12 21:29 UTC, merged