refactor(sql): remove old compiler
ibis-project/ibis pull request #8307
Opened 2024-02-12 11:08 UTC by kszucs

2024-02-12 21:08 UTC, cpcloud requested changes

2024-02-12 21:08 UTC, cpcloud commented on docs/posts/ibis-duckdb-geospatial/nyc_data.db.wal
Can you add a `gitignore` entry for this file and delete it?

2024-02-12 21:08 UTC, cpcloud commented on ibis/backends/impala/tests/snapshots/test_ddl_compilation/test_create_table_delimited/out.sql
Any idea why this is showing up as a binary file in GitHub?

2024-02-12 21:38 UTC, kszucs commented on ibis/backends/impala/tests/snapshots/test_ddl_compilation/test_create_table_delimited/out.sql
Possibly because of the null char:

```py
    stmt = ddl.CreateTableDelimited(
        "new_table",
        path,
        schema,
        delimiter="|",
        escapechar="\\",
        lineterminator="\0",
        database="foo",
        can_exist=True,
    )
```

2024-02-13 12:38 UTC, cpcloud approved these changes

2024-02-13 12:51 UTC, merged