depr: deprecate and warn on `legacy` udf usage
ibis-project/ibis pull request #8617
Opened 2024-03-11 14:41 UTC by ncclementi

This PR adds warnings for deprecation of `ibis.legacy.udf` for `v9.0`. I'm not super sure about the `instead` message for `elementwise`, suggestions are welcomed. 

According to the issue, seems like we are not going to support `analytic` and `reduction` on the new system, hence the empty comment on `instead`

- Closes https://github.com/ibis-project/ibis/issues/8567

2024-03-11 14:53 UTC, ncclementi commented
Whoops I forgot to add `with pytest.warns(FutureWarning)` in the corresponding tests. Coming right up

 `

2024-03-11 15:03 UTC, cpcloud requested changes

2024-03-11 15:03 UTC, cpcloud commented on ibis/legacy/udf/vectorized.py
> +@deprecated(as_of="9.0", instead="")
Builtin reductions can still be accessed. Perhaps it is fine (and helpful?) to say `"use the `@ibis.udf.agg.builtin` decorator"` or something similar.

2024-03-12 10:42 UTC, cpcloud approved these changes
Thanks!

2024-03-12 10:43 UTC, merged