feat(ir): more flexible dereferencing for join right-hand side
ibis-project/ibis pull request #8916
Opened 2024-04-09 09:49 UTC by kszucs

2024-04-09 10:45 UTC, kszucs commented
There is a more complicated test case in the impala test suite, inspecting it.

2024-04-09 12:47 UTC, kszucs commented
The multi-table dereference mapping calculation must be slightly smarter by tracking the distance from the target relations and picking the closest one (unless there are multiple ones at the same distance in which case an ambiguity error should be raised).

2024-04-15 17:17 UTC, cpcloud commented
@kszucs The two failures are pretty easy to fix. Otherwise, is this PR ready to go in?

2024-04-15 19:27 UTC, gforsyth commented
CI is green if @kszucs is happy with this.

2024-04-15 20:39 UTC, cpcloud requested changes

2024-04-15 20:39 UTC, cpcloud commented on ibis/backends/impala/tests/snapshots/test_sql/test_join_aliasing/out.sql
> +      ON `t10`.`d` = `t10`.`d`
This doesn't look correct to me. Should be `t8` as it was before.

2024-04-16 11:21 UTC, kszucs commented
No, I am not happy with this yet.

2024-04-18 11:18 UTC, cpcloud commented
Should we close this in favor of #8992?

2024-04-18 11:35 UTC, kszucs commented
Yes

2024-04-18 11:35 UTC, closed without merging