test: fix ArrayValue.remove() handling of NULLs
ibis-project/ibis pull request #9089
Opened 2024-04-30 18:44 UTC by NickCrews

2024-06-03 13:17 UTC, cpcloud requested changes
What is the fix here?

What was the original behavior? What's the new behavior? Why is it desired?

Blank PR descriptions make it really difficult to prioritize reviews on behavioral changes, please include them in those types of PRs!

2024-06-03 19:43 UTC, NickCrews commented
Sorry, this is very much a WIP, should have marked it as such. Added a very basic description to the OP.

2024-07-23 12:59 UTC, cpcloud commented
I think the postgres choice of using `IS NOT DISTINCT FROM` semantics in remove is inconsistent with `NULL` input behavior in nearly every other function and API.

If an argument is `NULL`, that means it's unknown and for consistency the only sane thing to do would be to return `NULL` in such cases.

Now, it's important to have convenience APIs, for example for removing all NULLs in an array.

I propose that we make the semantics of Ibis's `Array.remove` match those of Trino (which returns `NULL` when `NULL` is the element to search for), and add a new API `compress` (?) that strips all nulls from an array.

2024-07-28 07:57 UTC, NickCrews commented
@cpcloud just to be clear, currently `ibis.array([1, None, 2]).remove(2)` results in `[1]`. In this PR I just want to fix it so this results in `[1, None]`. Were you thinking I was trying to make `Array.remove(None)` strip NULLs? I am happy with not supporting that, and expecting users to do `Array.filter(_.notnull())`

2024-07-28 10:48 UTC, cpcloud commented
Ah, yep, I thought that's what you had in mind. Glad to see we're in agreement here!

2024-07-28 17:30 UTC, NickCrews commented
Yup that's my bad for a vague PR title and no description (I edited it to be more clear after I saw your confusion, you're not being gaslit here, it WAS confusing)

2024-07-31 13:52 UTC, cpcloud approved these changes

2024-07-31 15:17 UTC, merged

2024-07-31 15:17 UTC, NickCrews commented
Thanks @cpcloud for finishing this up!