refactor(api): refactor the implementation of windowing
ibis-project/ibis pull request #9200
Opened 2024-05-15 22:17 UTC by chloeh13q

## Description of changes

Refactor the implementation of windowing.

## Issues closed

#8847

2024-07-09 21:02 UTC, chloeh13q commented
@cpcloud Thanks for reviewing!

> are there any user-facing API changes, or is it only internals that have changed?
There are user-facing API changes, although the changes are pretty subtle. We're changing:
```python
expr = (
    t.window_by(time_col="i")
    .tumble(window_size=ibis.interval(minutes=15))
    .group_by(["window_start", "window_end", "g"])
    .aggregate(mean=_.d.mean())
)
```
to something like
```python
expr = (
    t.window_by(time_col="i")
    .tumble(window_size=ibis.interval(minutes=15))
    .group_by(["g"])
    .aggregate(mean=_.d.mean())
)
```
The big difference is that we're trying to hide columns like "window_start" "window_end" from the user (as well as providing more alternative syntax in a more Ibis-like manner, e.g., you can use both `.agg` and `.aggregate`, and you can put the groupby into aggregate as well now.

2024-07-16 15:35 UTC, cpcloud commented
@chloeh13q Can you rebase? I'll give a final review and this should be good to go after that.

2024-07-16 18:03 UTC, chloeh13q commented
@cpcloud Just rebased!

2024-07-16 21:04 UTC, cpcloud commented on ibis/backends/pyspark/tests/conftest.py
> +    for sq in con_streaming._session.streams.active:
This is a nice pattern for per-test cleanup, we might want to investigate this later for cleaning up temporary junk tables in certain cases. Not a priority, just a random thought.

2024-07-16 21:08 UTC, cpcloud requested changes
Didn't catch the `warnings` usage before, let's clean that up and then this is good to go!

2024-07-16 21:08 UTC, cpcloud commented on ibis/backends/pyspark/__init__.py
> +                warnings.warn("Watermark is not supported in batch mode")
Same here, let's not give warnings that have no effect.

2024-07-16 23:28 UTC, chloeh13q commented
@cpcloud Thanks for the review and feedback! I changed all the warnings to errors.

2024-07-18 12:40 UTC, merged

2024-07-18 12:40 UTC, cpcloud commented
Thanks!