feat: make Tables a Mapping
ibis-project/ibis pull request #9332
Opened 2024-06-07 19:27 UTC by NickCrews

Fixes https://github.com/ibis-project/ibis/issues/8672

2024-06-07 20:51 UTC, cpcloud requested changes

2024-06-07 20:51 UTC, cpcloud commented on ibis/expr/types/relations.py
> +        >>> ibis.options.interactive = True
```suggestion
```

This isn't necessary, you're not displaying any Ibis expressions.

2024-06-07 20:53 UTC, cpcloud requested changes

2024-06-07 20:53 UTC, cpcloud commented on ibis/tests/expr/test_table.py
> +
```suggestion
```

The test below seems sufficient. Alternatively you can put this assertion there.

2024-06-07 20:58 UTC, cpcloud commented
Are you planning on making `Table` a proper `Mapping` subclass, or are you just interested in the kwarg unpacking behavior?

2024-06-07 21:07 UTC, jcrist commented
If you're only interested in kwarg unpacking in `ibis.struct`, could we instead just make `ibis.struct(table)` work (adding a special case for a `Table` arg) rather than relying implicitly on kwarg unpacking? This will be both more efficient (since we won't need to do the work to validate all columns share a parent relation) and will let us avoid the addition of a `.keys()` method on a table (which IMO feels pretty weird).

FWIW my thoughts [here](https://github.com/ibis-project/ibis/pull/8671#issuecomment-2007967971) on making structs a mapping apply equally to the case here.

2024-06-07 22:39 UTC, NickCrews commented
I talk about most of these concerns in https://github.com/ibis-project/ibis/issues/8672.

> only interested in kwarg unpacking in ibis.struct

Not just that, I want to take advantage of generic ** unpacking to do `{"col1": "default_that_might_be_overwritten", **table, "col2": "always_this_val"}`.

2024-06-29 19:22 UTC, NickCrews commented
closing for now as stale.

2024-06-29 19:22 UTC, closed without merging