enh: datafusion enhancements
ibis-project/ibis pull request #9544
Opened 2024-07-10 14:10 UTC by mesejo

- change collect to execute_stream, `collect` pulls all the data in memory, `execute_stream` only pulls partial data (reducing memory consumed)

- fix creation of table with uppercase name and object (`pa.Table`, `pd.DataFrame`, etc)

- remove the use of strings literal for dialect

2024-07-10 21:06 UTC, cpcloud requested changes
LGTM except for the one comment, thanks!

2024-07-10 21:06 UTC, cpcloud commented on ibis/backends/datafusion/__init__.py
> +            table_ident = str(sg.table(name, db=database, quoted=quoted))
```suggestion
            table_ident = sg.table(name, db=database, quoted=quoted).sql(self.dialect)
```

Just to be safe here and make sure we're using the datafusion dialect.

2024-07-10 21:23 UTC, mesejo commented
Thanks for the review @cpcloud

2024-07-15 13:28 UTC, cpcloud approved these changes

2024-07-15 13:29 UTC, cpcloud commented
Sorry for the delay, merging!

2024-07-15 13:29 UTC, merged